import time
from io import BytesIO


def generate_markdown_report(company_name: str, data: dict) -> str:
    """Generate a full Markdown report."""
    timestamp = time.strftime("%B %d, %Y at %H:%M")
    md = f"""# AI Intelligence Report: {company_name}
*Generated on {timestamp} by AI Research Agent*

---

## 1. Company Overview

{data.get('overview', 'N/A')}

---

## 2. Key Business Information

{data.get('biz_info', 'N/A')}

---

## 3. Potential Business Challenges

{data.get('challenges', 'N/A')}

---

## 4. AI Opportunities

{data.get('ai_opps', 'N/A')}

---

## 5. Personalized CEO Pitch

{data.get('pitch', 'N/A')}

---

*Report generated by AI Research Agent | Powered by Ollama (local AI) + DuckDuckGo*
"""
    return md


def generate_pdf_report(company_name: str, data: dict) -> bytes:
    """Generate a PDF report using ReportLab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable, PageBreak
    )

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=22,
        textColor=colors.HexColor("#1e3a5f"),
        spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        "SubTitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#6c757d"),
        spaceAfter=20
    )
    heading_style = ParagraphStyle(
        "HeadingStyle",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#0d6efd"),
        spaceBefore=16,
        spaceAfter=8,
        borderPad=4
    )
    body_style = ParagraphStyle(
        "BodyStyle",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
        spaceAfter=8,
        textColor=colors.HexColor("#212529")
    )

    story = []
    timestamp = time.strftime("%B %d, %Y at %H:%M")

    story.append(Paragraph(f"AI Intelligence Report", title_style))
    story.append(Paragraph(company_name, ParagraphStyle(
        "CompanyName", parent=styles["Title"], fontSize=18,
        textColor=colors.HexColor("#0d6efd"), spaceAfter=4
    )))
    story.append(Paragraph(f"Generated on {timestamp}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#0d6efd")))
    story.append(Spacer(1, 16))

    sections = [
        ("1. Company Overview",          data.get("overview", "")),
        ("2. Key Business Information",   data.get("biz_info", "")),
        ("3. Potential Business Challenges", data.get("challenges", "")),
        ("4. AI Opportunities",           data.get("ai_opps", "")),
        ("5. Personalized CEO Pitch",     data.get("pitch", "")),
    ]

    for heading, content in sections:
        story.append(Paragraph(heading, heading_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dee2e6")))
        story.append(Spacer(1, 6))

        for line in content.split("\n"):
            line = line.strip()
            if line:
                safe_line = (
                    line.replace("&", "&amp;")
                        .replace("<", "&lt;")
                        .replace(">", "&gt;")
                )
                if safe_line.startswith("•") or safe_line.startswith("-") or safe_line.startswith("*"):
                    story.append(Paragraph(f"&nbsp;&nbsp;{safe_line}", body_style))
                elif safe_line.endswith(":") and len(safe_line) < 80:
                    story.append(Paragraph(f"<b>{safe_line}</b>", body_style))
                else:
                    story.append(Paragraph(safe_line, body_style))

        story.append(Spacer(1, 12))

    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dee2e6")))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "Report generated by AI Research Agent | Powered by Ollama (local AI) + DuckDuckGo",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=9,
                       textColor=colors.HexColor("#6c757d"), alignment=1)
    ))

    doc.build(story)
    return buffer.getvalue()
